### ISSUE TITLE
WireGuard-UI URL ist nicht aufrufbar

### ISSUE THREAD

**Issue by JHD47804** [KleSecGmbH/ioBroker#2]
Hallo,
ich habe die Installation von Wireguard haargenau nach der Anleitung ausgeführt, jedoch kann ich die IP-Adresse mit Port 5000 nicht aufrufen.
Woran kann das liegen?
Bitte um Hilfe, danke.

**Comment by KleSecGmbH** [comment]
Bitte zeig einmal den Output von:
`wg`

**Comment by JHD47804** [comment]
root@Wireguard:~# wg
interface: wg0
  public key: /RSLMDn7ukyGDPj6x5asaNDlUDC4eM1SvBRnJt7Pimo=
  private key: (hidden)
  listening port: 7774

peer: 58ImlBdJvwF8B46hhhSJPZjg3wB2sR9HApRoYGJqP3Y=
  preshared key: (hidden)
  allowed ips: 10.7.0.2/32
root@Wireguard:~#

**Comment by KleSecGmbH** [comment]
Ok das ist schonmal gut. Was sagt 
`cd /root/wireguard-ui`
`docker-compose up `

**Comment by JHD47804** [comment]
root@Wireguard:~/wireguard-ui# docker-compose up
Creating wgui ... 

ERROR: for wgui  "host" network_mode is incompatible with port_bindings

ERROR: for wg  "host" network_mode is incompatible with port_bindings
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.27.4', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 67, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 126, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1070, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1051, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 643, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 625, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 557, in execute_convergence_plan
    return self._execute_convergence_create(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 471, in _execute_convergence_create
    containers, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 476, in <lambda>
    lambda service_name: create_and_start(self, service_name.number),
  File "/usr/lib/python3/dist-packages/compose/service.py", line 455, in create_and_start
    container = service.create_container(number=n, quiet=True)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 328, in create_container
    container_options = self._get_container_create_options(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 934, in _get_container_create_options
    container_options['host_config'] = self._get_container_host_config(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1009, in _get_container_host_config
    return self.client.create_host_config(
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 598, in create_host_config
    return HostConfig(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/types/containers.py", line 338, in __init__
    raise host_config_incompatible_error(
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings

**Comment by KleSecGmbH** [comment]
OK, bitte installier einmal WireguardUI ohne Docker aus meinem anderen Repository.

`wget https://raw.githubusercontent.com/KleSecGmbH/ioBroker/dev/wireguard/installer-wgui.sh -O installer-wgui.sh && bash installer-wgui.sh
`

**Comment by JHD47804** [comment]
ok, vielen Dank. Mache ich und melde mich.

**Comment by JHD47804** [comment]
es hat funktioniert, vielen Dank. Kannst du mir bitte den Link schicken aus den anderen Repository. Ich habe nur den alten von 08.11.2021, würde mir gerne die Schritte nochmal anqucken.

**Comment by KleSecGmbH** [comment]
Das ist der Link zum WireGuard UI Installer der aktuell im test ist. Den hast du gerade installiert. Ich werde noch diese Woche den Proxmox Installer Updaten, da immer wieder Probleme mit Docker auftreten.

https://raw.githubusercontent.com/KleSecGmbH/ioBroker/dev/wireguard/installer-wgui.sh
